Docs: Convert current pbench MarkDown content to readthedocs and reStructuredText format
distributed-system-analysis/pbench pull request #1730
Opened 2020-07-23 02:00 UTC by haoweiqiu

Inspired by Google SoD project idea lists, this PR converts current pbench MarkDown content to readthedocs and reStructuredText format. I could finish the update of pbench documentation if my project is selected. 
The ReadtheDocs link is: https://pbench-docs.readthedocs.io/

2020-07-27 23:52 UTC, portante commented
Thanks @haoweiqiu!  I'll review soon.

2020-07-27 23:59 UTC, portante commented
Can you also consider the `gh-pages` branch content?  Though we are looking to merge https://github.com/distributed-system-analysis/pbench/pull/1586 soon.

2020-07-28 21:56 UTC, haoweiqiu commented
@portante Thank you very much for the comment! I'll look into #1586 and modify Read the Docs.

2020-09-03 20:55 UTC, dbutenhof reviewed
Just skimmed this; comments and questions on content and formatting.

Maybe I'm unclear on the context of this review, but I see missing "pbench-" prefixes on tools, jumbled sets of command lines without line breaks, and odd sample output including Pbench debug statements. Just a few examples are marked in this review. I'll read more later.

2020-09-28 18:02 UTC, portante requested changes
Good start.

This adds a new directory, `docs`.  What are you thinking we should do with the existing `doc` directory?  I was hoping we could make these changes in the `doc` directory, just moving all of the current "mark down" files we have (`.md`) to reStructuredText that is supported by GitHub.

Does GitHub's rendering of the new documents work as expected?

2020-10-27 21:24 UTC, ndokos requested changes
It seems that this is based on a very old set of docs that does not follow current conventions. It needs a fair amount of alterations (the lack of the `pbench-` prefix on most commands is the most obvious omission).

2020-10-27 21:24 UTC, ndokos commented on docs/conf.py
> +copyright = '2020, Haowei'
Shouldn't the copyright be assigned to a RH entity?

2020-10-27 21:24 UTC, ndokos commented on docs/pbench-agent.rst
> +   move-results
pbench- prefix missing

2020-10-27 21:24 UTC, ndokos commented on docs/pbench-agent.rst
> +   copy-results
pbench- prefix missing

2020-10-27 21:24 UTC, ndokos commented on docs/pbench-agent.rst
> +   move-results
pbench- prefix missing on last three lines

2020-10-27 21:24 UTC, ndokos commented on docs/pbench-agent.rst
> +These are now specified in the config file
This whole section does not sound right: `base` does set a bunch of variables but most of these are not specified in the config file. In particular, `date`, `hostname`, `results_repo` and `results_repo_dir` are not specified in the config file. The last two I can't find anywhere, either in the config file or in `base`.

2020-10-27 21:24 UTC, ndokos commented on docs/pbench-agent.rst
> +``/opt/pbench-agent/config/pbench.conf``.
The config file is `/opt/pbench-agent/config/pbench-agent.cfg`.

2020-10-27 21:24 UTC, ndokos commented on docs/pbench-agent.rst
> +``register-tool-set``) is:
pbench-

2020-10-27 21:35 UTC, ndokos commented
What is the process of publishing these documents on `readTheDocs`?

2023-07-10 05:04 UTC, pravins commented
This has been fixed with https://github.com/distributed-system-analysis/pbench/pull/3428
Feel free to reopen if something is missing.

2023-07-10 05:04 UTC, closed without merging