OVS-Hrdware-Offload flow support in openvswitch-datalog
distributed-system-analysis/pbench pull request #1772
Opened 2020-09-02 10:57 UTC by pradiptapks

2020-09-02 22:03 UTC, npalaska commented
Hi, can you please provide a short description for your PR

2020-09-03 00:16 UTC, portante requested changes
Can you add a bit more about the need for this data, and what is to be done with it, in the body of the commit message, and then update PR description?  Thanks!

2020-09-03 00:16 UTC, portante commented on agent/tool-scripts/datalog/openvswitch-datalog
> +
Let's consider merging these two loops since the loop control variable is the same.

2020-09-03 00:19 UTC, portante commented
Can you also add support for processing your data in `agent/tool-scripts/postprocess/openvswitch-postprocess`?

2020-09-03 03:23 UTC, not4win commented
As part of future work, we'll be integrating pbench with pcp. The metrics collected from openvswitch-datalog will instead be collected by openvswitch PMDA in pcp. 
Link to it's code and documentation : https://github.com/performancecopilot/pcp/tree/master/src/pmdas/openvswitch

2020-09-03 03:34 UTC, portante commented
> Link to it's code and documentation : https://github.com/performancecopilot/pcp/tree/master/src/pmdas/openvswitch

@pradiptapks, can you take a look at the PCP code and either file an issue or add a PR to that code add the same metrics?

2020-09-03 06:38 UTC, pradiptapks commented
> Hi, can you please provide a short description for your PR

2020-09-03 06:38 UTC, closed without merging

2020-09-03 09:13 UTC, pradiptapks commented
Hi @portante,

Due to git rebase issue, this branch was deleted and unable to reopen the PR.
Please continue to refer the new PR with description details: https://github.com/distributed-system-analysis/pbench/pull/1774

I will review the code for pcp and will update the suggestion as well. Since