[WIP] Convert shell scripts to python
distributed-system-analysis/pbench pull request #1810
Opened 2020-09-21 22:41 UTC by zulcss

Converted the following scripts to python:

 pbench-list-triggers = pbench.cli.agent.commands.triggers.list:main
   pbench-register-tool-trigger = pbench.cli.agent.commands.triggers.register:main
   pbench-send-tools = pbench.cli.agent.commands.tools.process:send
   pbench-start-tools = pbench.cli.agent.commands.tools.process:start
   pbench-stop-tools = pbench.cli.agent.commands.tools.process:stop
   pbench-kill-tools = pbench.cli.agent.commands.tools.process:kill
   pbench-avg-stddev = pbench.cli.agent.commands.stddev:main
   pbench-log-timestamp = pbench.ci.agent.commands.timestamp:main
   pbench-cleanup = pbench.cli.agent.commands.cleanup:main
   pbench-agent-config-activate = pbench.cli.agent.commands.config.config:main
   pbench-agent-config-ssh-key = pbench.cli.agent.commands.config.ssh:main
   pbench-clear-tools = pbench.cli.agent.commands.tools.clear:main
   pbench-list-tools = pbench.cli.agent.commands.tools.list:main
   pbench-register-tool = pbench.cli.agent.commands.tools.register:main
   pbench-register-tool-set = pbench.cli.agent.commands.tools.toolset:main
   pbench-add-metalog-option = pbench.cli.agent.commands.log.metalog:main
   pbench-postprocess-tools = pbench.cli.agent.commands.tools.postprocess:main
   pbench-collect-sysinfo = pbench.cli.agent.commands.sysinfo.collect:main
   pbench-metadata-log = pbench.cli.agent.commands.log.metadata:main

2020-09-24 17:19 UTC, portante requested changes
How does this work relate to PR #1770?  Is it a replacement?  Does it layer on top of that work?  Or does it already include that work?

Could we consider one commit for all the non-shell script conversion work, and then keep the individual commits for each shell script conversion?

2020-09-24 17:24 UTC, zulcss commented
> How does this work relate to PR #1770? Is it a replacement? Does it layer on top of that work? Or does it already include that work?
> 
> Could we consider one commit for all the non-shell script conversion work, and then keep the individual commits for each shell script conversion?

This commit builds on top of 1770, yeah i can merge these together.

2020-09-25 21:00 UTC, dbutenhof reviewed
OK, enough for today. Some comments follow... More later.

2020-09-28 20:07 UTC, dbutenhof requested changes

2021-01-15 20:48 UTC, closed without merging