Setup base classes
distributed-system-analysis/pbench pull request #1842
Opened 2020-10-05 14:10 UTC by zulcss

Stub in base classes for various CLI utils that we will
be replacing shell scripts with python scripts.

Since there are alot of different shell scripts to convert
I grouped the various commands into sub-classes from the BaseCommand
since alot of the shell scripts are re-using the same code as well.
So it made sense to me.

Signed-off-by: Charles Short <chucks@redhat.com>

2020-10-05 14:28 UTC, dbutenhof reviewed
Is this just a placeholder to help with parallel development? The class names seem to have appeared before (aside from things like `SysInfoCommand` vs `SysinfoCommand`), but always pulling in mix-ins, and with extended behavior.

I think maybe I like having them centralized, although I might prefer having them separated within a single directory.

If these classes remain essentially just renames of the base command class with no extended behaviors, then this plethora seems like unnecessary confusion... but if the classes are going to gain more than trivial behavior, this is a lot of classes to be crammed into a single file.

In any case, this "colo" class style can complicate navigation by losing any obvious link from class to source file.

Maybe even if you could just extend the git comment to provide more context on your intent here?

2020-10-05 15:47 UTC, portante requested changes

2020-10-05 15:47 UTC, portante commented on lib/pbench/cli/agent/core.py
> +class LogCommand(BaseCommand):
Is there a reason that we need all the command classes in the same file?  Why not have a `base.py` and a `tool.py`, `log.py`, etc?  If there is a good reason to have them all in the same file, great; however, it is not obvious why they need to be.

Having them in separate files means that we can add and convert commands as necessary without merge conflicts as we work.

2020-10-15 12:26 UTC, zulcss commented
This isnt needed anymore

2020-10-15 12:26 UTC, closed without merging