Tell pbr to stop creating AUTHORS & ChangeLog
distributed-system-analysis/pbench pull request #1844
Opened 2020-10-06 02:03 UTC by portante

When running tests, stop creating the `AUTHORS` and `ChangeLog` files.  See https://docs.openstack.org/pbr/latest/user/packagers.html#versioning.

2020-10-06 11:44 UTC, dbutenhof submitted a review, later dismissed

2020-10-06 20:34 UTC, npalaska approved these changes

2020-10-06 20:40 UTC, ndokos requested changes
I don't know what `usedevelop` used to do, so I don't understand why the deletion makes  sense here or how it is related to the ostensible reason for the PR. A comment would help.

2020-10-06 20:51 UTC, dbutenhof approved these changes

2020-10-06 21:15 UTC, npalaska submitted a review, later dismissed

2020-10-07 00:10 UTC, ndokos approved these changes

2020-10-07 04:51 UTC, npalaska approved these changes

2020-10-07 10:27 UTC, merged