Design fixes for Documentation page
distributed-system-analysis/pbench pull request #1904
Opened 2020-10-22 07:50 UTC by anishaswain

Fixes:
- On hovers, need to turn to the light teal colour (#1BC1C9), not the dark 
- Several instances of Overpass font converted to Work Sans
- There was too much space around the cards (they were not left-aligned with the rest of the page content), and the three cards do NOT need to be sitting on an additional shadow card.
- The cards should all auto-adjust to be the height of the tallest card, making them all the same height 
- The three recent meetings cards were too far apart, so switched the spacing to `margin: var( --pf-global--spacer--md);`
- The `quicklinks` should be left-aligned. 
- The dropdowns for the cards (Pbench agent, Pbench server, and Dashboard) should NOT use all caps -- use sentence case.
- There was a bit of an issue with the interaction of the dropdown on the cards as well. When the card is expanded, the icon would be down, and it needs to swap to pointing to the right on closing.

2020-10-22 17:56 UTC, portante approved these changes

2020-10-22 17:56 UTC, portante commented
@anishaswain, can you rebase this PR?

2020-10-22 17:57 UTC, portante requested changes
While this looks ready to go, it needs a rebase.  Thanks!

2020-10-26 18:36 UTC, npalaska approved these changes
Needs squashing I guess

2020-10-26 18:43 UTC, dbutenhof commented on index.css
> + .div4{
Doesn't "div4" seem like a fairly generic name for a very specific background pattern?

2020-10-27 05:43 UTC, anishaswain commented
closing in reference to #1917

2020-10-27 05:43 UTC, closed without merging