Agent logging
distributed-system-analysis/pbench pull request #1926
Opened 2020-10-28 14:15 UTC by zulcss

Rejig logging a bit so that we set the agent logging in the base class.

2020-10-28 14:38 UTC, dbutenhof requested changes
GitHub won't let me comment on the line, but `pbench-clear-tools` should no longer be importing `logging` ... that's making LGTM unhappy, and nobody likes it when LGTM is unhappy. :-(

2020-10-28 14:57 UTC, dbutenhof approved these changes
Well that ought to satisfy the scanner. Maybe by next year, Travis will have finished, and you can merge...

2020-10-28 15:03 UTC, npalaska submitted a review, later dismissed

2020-10-28 15:32 UTC, portante submitted a review, later dismissed

2020-10-29 14:29 UTC, dbutenhof approved these changes

2020-10-29 17:04 UTC, npalaska approved these changes

2020-10-29 17:25 UTC, merged