Rejig functional unit tests
distributed-system-analysis/pbench pull request #1941
Opened 2020-11-02 14:13 UTC by zulcss

Use pytest helpers to create a reproducable envrionment
that we do with the shell scripts. Eventually, this
will replace the shell scripts and the gold files
that we *shudder* use.

Signed-off-by: Charles Short <chucks@redhat.com>

2020-11-02 18:52 UTC, portante approved these changes

2020-11-02 18:52 UTC, portante requested changes
Needs a rebase it seems.

2020-11-02 19:08 UTC, dbutenhof approved these changes

2020-11-04 14:04 UTC, portante approved these changes
Looks good!

2020-11-04 14:36 UTC, dbutenhof approved these changes

2020-11-04 14:46 UTC, merged