Fix spec file and ansible roles
distributed-system-analysis/pbench pull request #1994
Opened 2020-11-18 17:09 UTC by ndokos

This is a forward port of PR #1988 (which was against the b0.69 branch) to master branch.

When I simplified the spec file back in June, I went a bit too far
and lost the js files that we need for visualization. Some of these have
been added back: the rest are needed for the (very) old web-server version
only.

The firewall role added http and https services to the "permanent" setup
but neglected to reload the rules, so they were not valid for the current
boot (although they would work fine after a reboot :-) ).

The pbench-tarballs link from /var/www/html to the archive was not created
by the playbook (it was added manually to the production server). It is
now added by the playbook.

2020-11-18 17:12 UTC, portante approved these changes

2020-11-23 11:03 UTC, riya-17 submitted a review, later dismissed

2020-11-30 21:53 UTC, portante requested changes
@ndokos, needs a rebase ...

2020-12-01 20:22 UTC, portante approved these changes

2020-12-01 21:11 UTC, portante requested changes
@ndokos, needs a rebase due to other merges ...

2020-12-03 14:06 UTC, ndokos commented
Rebased.

2020-12-03 14:57 UTC, portante approved these changes

2020-12-03 15:08 UTC, dbutenhof approved these changes

2020-12-03 15:08 UTC, dbutenhof commented on server/ansible/roles/pbench-server-firewall/tasks/main.yml
>      - http
Just as a note (doesn't need to be worked out now), but we're going to need to punch a hole for the API port too, currently 8001 by default -- but we should create a fact to pull this from the target config file.

I also wonder whether it'd be better to set up a proxy configuration that will let us split the /api URI path from other accesses and drive everything off http/https without using a separate port, which would make more sense.

(Further note, as we move forward to user authentication, we'll probably want to drop http entirely.)

2020-12-03 17:10 UTC, merged

2021-05-05 18:49 UTC, ndokos commented
Fixes #1989.