Add support for overriding TM bind hostname
distributed-system-analysis/pbench pull request #2008
Opened 2020-11-25 17:33 UTC by portante

We add support for a caller to override the bind host name used by the Redis Server and Tool Data Sink using the `PBENCH_TM_BIND_HOSTNAME` environment variable.

We also ensure the list of hostnames used by the Redis Server do not map to the same IP address.

2020-11-25 17:34 UTC, portante commented
@RobertKrawitz, I think this should solve the bind host problem we debugged.

2020-11-30 19:49 UTC, ndokos approved these changes

2020-11-30 20:06 UTC, dbutenhof requested changes

2020-11-30 20:06 UTC, dbutenhof commented on agent/util-scripts/pbench-tool-meister-start
> +        tm_bind_hostname_ip = None
The assignment isn't necessary as `tm_bind_hostname_ip` isn't referenced outside the `else`. LGTM is complaining. However, a log might be handy here? In any case, you should fix the LGTM alert.

2020-11-30 20:17 UTC, npalaska commented on agent/util-scripts/pbench-tool-meister-start
> +        tm_bind_hostname_ip = None
I think this line wont do anything since we dont have a `finally` block

2020-11-30 22:13 UTC, npalaska approved these changes

2020-12-01 12:51 UTC, dbutenhof submitted a review, later dismissed

2020-12-01 16:21 UTC, dbutenhof approved these changes

2020-12-01 18:49 UTC, RobertKrawitz commented
/lgtm

2020-12-01 19:34 UTC, dbutenhof approved these changes

2020-12-01 19:35 UTC, ndokos approved these changes

2020-12-01 19:53 UTC, merged