Replace pbench-clear-tools tests
distributed-system-analysis/pbench pull request #2012
Opened 2020-12-01 13:47 UTC by zulcss

Replace pbench-clear-tools unittests with pytest unittests.

Signed-off-by: Charles Short <chucks@redhat.com>

2020-12-01 15:17 UTC, portante requested changes
Looks good ... could you add a function doc text for each test to describe the goal of the test?  Perhaps taken from the comments that were in `unittests`?

2020-12-01 15:19 UTC, dbutenhof approved these changes

2020-12-02 13:48 UTC, dbutenhof approved these changes
It would be nice to see doc strings on the unit test cases to explain exactly what's being tested; but it's looking good.

2020-12-02 17:47 UTC, portante requested changes
And it needs a rebase ...

2020-12-02 17:47 UTC, portante commented on lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py
> +    command = ["pbench-clear-tools", "--remote=fubat2"]
Looks like the output from this test does not match the original.  Could that be because we have `fubat2` here instead of `fubar2`?

2020-12-02 17:47 UTC, portante commented on lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py
> +def test_clear_tools_test13(monkeypatch, agent_config, pbench_run, pbench_cfg):
Perhaps a doc string could be: "Remove one tool group leaving the default".

2020-12-02 17:47 UTC, portante commented on lib/pbench/test/functional/agent/cli/commands/tools/test_clear_tools.py
> +def test_clear_tools_test12(monkeypatch, agent_config, pbench_run, pbench_cfg):
Perhaps the doc string could be: "Remove all tools from all tool groups".

2020-12-02 18:29 UTC, portante requested changes
Looks good, but still needs a rebase.

2020-12-02 18:46 UTC, portante approved these changes

2020-12-02 19:35 UTC, dbutenhof approved these changes

2020-12-02 20:18 UTC, merged