Make the backup cron job run every minute
distributed-system-analysis/pbench pull request #2038
Opened 2020-12-14 03:14 UTC by ndokos

2020-12-14 03:23 UTC, portante approved these changes

2020-12-14 09:20 UTC, riya-17 approved these changes

2020-12-14 12:48 UTC, portante requested changes
Need updates to fix the unit tests ...

2020-12-15 19:24 UTC, dbutenhof approved these changes

2020-12-15 21:13 UTC, portante approved these changes

2020-12-15 21:13 UTC, merged