Ensure `fio` uses full unix timestamps
distributed-system-analysis/pbench pull request #2520
Opened 2021-10-30 05:12 UTC by portante

Addresses issuse #913 and fixes issue #1021.

2021-11-01 12:02 UTC, dbutenhof reviewed
The git comment doesn't explain the change from "xy" to "timeseries" charting; should it?

And neither change has any impact on the legacy test output other than echoing the options; which is slightly concerning as we're getting no proof that these are accomplishing anything. I'm a little surprised there are no other file diffs detected.

2021-11-01 16:13 UTC, webbnh requested changes
I second Dave's comments:  I don't see any code (or configuration) change which would have prompted the change from "xy" plot to "timeseries" in `test-32.txt`.  And, I don't see anything in this PR which indicates that it addressed the problem reported in #1021.

2021-11-01 21:41 UTC, portante commented
> The git comment doesn't explain the change from "xy" to "timeseries" charting; should it?

I updated the git commit message and the PR description to cover this.

> And neither change has any impact on the legacy test output other than echoing the options; which is slightly concerning as we're getting no proof that these are accomplishing anything. I'm a little surprised there are no other file diffs detected.

We don't run `fio` as part of the legacy tests, so we only update the `fio.job` file to ensure it is present.  Also updated the git commit message and the PR description.

2021-11-01 21:42 UTC, portante commented
> I second Dave's comments: I don't see any code (or configuration) change which would have prompted the change from "xy" plot to "timeseries" in `test-32.txt`.

Answered in the git commit message and PR description updates.

> And, I don't see anything in this PR which indicates that it addressed the problem reported in #1021.

Due to the fact that we don't run `fio` as part of the existing legacy tests, we can't demonstrate that at this time, other than to ensure the proper option is present in the generated `fio.job` files.

2021-11-02 11:30 UTC, dbutenhof approved these changes

2021-11-02 15:11 UTC, webbnh approved these changes
👍

2021-11-02 16:10 UTC, portante reviewed
Had to rebase.

2021-11-02 16:33 UTC, dbutenhof approved these changes

2021-11-02 16:55 UTC, webbnh approved these changes
> Had to rebase.

You didn't want to use the "Rebase and merge" button?  (Or, even the "Squash and merge" button?)

2021-11-02 17:12 UTC, merged