Increase Prom retention in visualizers
distributed-system-analysis/pbench pull request #2536
Opened 2021-11-09 22:41 UTC by jeniferh

Increase Prom retention to 1yr. 

This is especially useful for the "post" PromGrafVisualizer option where you may be looking at older data. Without an increase in retention, when running the visualizer image Prom can delete any original data (provided by the volume mount) older than the default 15d -- ask me how I know :), luckily I had a backup copy!

2021-11-09 22:43 UTC, jeniferh commented
@Maxusmusti thoughts on this?

2021-11-09 22:52 UTC, Maxusmusti reviewed
LGTM, makes sense. I'll build and test to make sure it's all still working as expected, but it seems like it should be fine.

2021-11-09 23:03 UTC, jeniferh commented
Thanks! I tested locally so hopefully no surprises.

2021-11-10 04:03 UTC, portante approved these changes
This is a good short-term fix, but the visualizer should find a way to ensure when looking at older data sets they are not modified in any way.  Having something automatic, which would not require a hard-coded setting would be more supportable.

2021-11-10 16:37 UTC, webbnh approved these changes
I hope that 1 year is long enough...is there any reason not to make it longer?  (Is there an "infinity" or "no-limit" value?)

2021-11-10 17:07 UTC, jeniferh commented
I will poke around to see if there are other ways to extend Prom retention.. but I figured if the data is older than 1yr is it even that relevant anyway? ;)

2021-11-10 18:56 UTC, jeniferh commented
I did try a readonly volume mount but that won't work:
`caller=query_logger.go:87 component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: read-only file system"`

2021-11-10 21:55 UTC, portante commented
@Maxusmusti said he was going to review.  I'll merge following that review.

2021-11-11 00:56 UTC, Maxusmusti requested changes
I've built and pushed updated images, everything should be good to go (after a rebase, branch out of date). I've also had to change PCP version for pcp-graf-visualizer, so you could go into DockerfilePostPCP and change to `ARG PCP_VERSION="5.3.4-2.fc33"` (otherwise I'll do it in a seperate PR after this is merged).

2021-11-11 02:36 UTC, portante commented
> I've also had to change PCP version for pcp-graf-visualizer, so you could go into DockerfilePostPCP and change to `ARG PCP_VERSION="5.3.4-2.fc33"` (otherwise I'll do it in a seperate PR after this is merged).

@Maxusmusti, could we consider approving this now and work that in a separate PR?

2021-11-11 09:05 UTC, Maxusmusti commented
> > I've also had to change PCP version for pcp-graf-visualizer, so you could go into DockerfilePostPCP and change to `ARG PCP_VERSION="5.3.4-2.fc33"` (otherwise I'll do it in a seperate PR after this is merged).
> 
> @Maxusmusti, could we consider approving this now and work that in a separate PR?

Sounds good, just the rebase then 👍

2021-11-11 12:57 UTC, merged