Sort python requirements files
distributed-system-analysis/pbench pull request #2644
Opened 2022-02-26 02:51 UTC by portante

Broken out from PR #2551.

2022-02-26 13:28 UTC, portante commented
Rebased on PR #2646 to provide a layering for review of the final work in #2551.

2022-02-28 12:33 UTC, dbutenhof requested changes

2022-02-28 12:33 UTC, dbutenhof commented on lib/pbench/common/selinux.py
> +            return False
Is this what you want? My investigations when I wrote the file tree mocks showed that the real selinux returns integer `0` or `1`, not `True` or `False`.

2022-02-28 19:05 UTC, webbnh approved these changes
I'm not sure what it means to approve a draft PR, but I'm gonna try it....

2022-02-28 21:34 UTC, dbutenhof submitted a review, later dismissed

2022-02-28 22:43 UTC, portante commented
> I'm not sure what it means to approve a draft PR, but I'm gonna try it....

The goal is to make sure this PR does not get submitted with the commit that is taken from PR #2646.  Once that is merged, then we can consider merging this one.

Boy do I wish we had Gerrit.

2022-02-28 23:28 UTC, webbnh commented
> The goal is to make sure this PR does not get submitted with the commit that is taken from PR #2646.

That's fair.

I wanted to see whether my approval got revoked when you marked this ready to review, but your rebase cleared it....

2022-03-01 16:28 UTC, portante reviewed
Okay, ready for review.

2022-03-01 16:51 UTC, dbutenhof approved these changes

2022-03-01 16:53 UTC, webbnh approved these changes
👍

2022-03-01 16:59 UTC, merged