Add environment variable to ignore check_install_rpm
distributed-system-analysis/pbench pull request #2717
Opened 2022-03-30 12:25 UTC by ldoktor

sometimes people might need to disable the "check_install_rpm" check to
use non-rpm tools or tool of a different version. Let's add an
environment variable "PBENCH_IGNORE_CHECK_INSTALL_RPM" to ignore
check_install_rpm failures while adding a note to the log about
not-running-the-expected-tool-version so people need to reproduce with
the expected tool version to file issues.

Signed-off-by: Lukáš Doktor <ldoktor@redhat.com>

2022-03-30 21:49 UTC, webbnh reviewed
Having the "big hammer" issue a warning instead of skipping the check altogether is an improvement, but I think I would prefer that the change(s) be made at the invocation(s) of `check_install_rpm()` rather than inside it.

That is, if the problem at the moment is with `pbench-linpack`, perhaps we should place the change there, rather than in `agent/base`.

2022-03-31 06:21 UTC, ldoktor commented
Hello @webbnh, my motivation was to avoid custom handling per-script, which could lead to different global variables being used. This way we have a central place where to control the handling while only warning in case the check_rpm fails. I'd actually benefit of this in fio as well, because RHEL9 comes with officially unsupported fio but I'm actually using it very well (see the sed example above on how I actually run my scripts to avoid check_rpm failures).

Anyway the only not-really-working script for me right now is the pbench-linpack so if you really insist on in-script handling I'll change that for that script only, but please take a second thought of the central place benefit first...

2022-03-31 14:42 UTC, webbnh commented
> my motivation was to avoid custom handling per-script, which could lead to different global variables being used.

Understood.  And, my motivation was to make sure that we used the right size hammer.  😀

I'm not too concerned about us ending up with different switches, unless they are warranted -- that's part of what PR review is for.  😉  But, I think it would be best to have the right control in the right place, and global controls often end up being problemmatic.

> I'd actually benefit of this in fio as well

This contributes weight toward having a centralized facility, but, modifying two files is not that hard relative to modifying one.  (You can claim that it is twice as hard, but it has only a fourth of the impact of doing it globally.... 🙂)
 
> the only not-really-working script for me right now is the pbench-linpack [...] please take a second thought of the central place benefit first...

My principal reservation stemmed from thinking that `check_install_rpm()` was being used for things other than benchmark workloads (e.g., data collection tools), and that it was being used multiple times per run (meaning that having a single "on/off" switch was too coarse a granularity).  However, I haven't been able to find references to it outside the benchmark scripts, so perhaps your approach is reasonable.  I'll look some more.

2022-04-02 01:46 UTC, portante commented
> btw, @portante, in my testing I'm usually using following "hack" to avoid pbench failures:
> 
> ```python
>             ver = session.cmd("{ rpm -q %s || rpm -q pbench-%s; } | tail -n 1"
>                               % (self.test, self.test)).strip().split('-')[1]
>             session.cmd("sed -i '/^\\[%s]/,/^\\[/{"
>                         "s/^version[[:space:]]*=.*/version = %s/}' "
>                         "/opt/pbench-agent/config/pbench-agent-default.cfg"
>                         % (self.test, ver))
> ```

So you could also modify the `/opt/pbench-agent/config/pbench-agent.cfg` file to add the same section from the `pbench-agent-default.cfg` file with the specific option you want changed.

I would not recommend modifying the `pbench-agent-default.cfg` file, since we provide the `pbench-agent.cfg` for that purpose.

> 
> unfortunately that won't help with pbench-linpack as that one doesn't use config to get the version and besides it requires files to be located in the directory based on the rpm version (which is not the case for the current version. Anyway I'm open to any suggestion on how to achieve what I need while keeping you guys confidence that you don't need to support all possible combinations. I like the way kernel handles that by allowing any modifications while tainting the build so when you file a bz they can just ask you to re-run it without your modules.

Sure.  We need a "relax" mode.

I'll post a PR with what I am thinking.

2022-04-02 02:08 UTC, portante requested changes
Consider using something like: https://github.com/ldoktor/pbench/pull/3.

2022-04-05 12:04 UTC, ldoktor commented
Thank you, Peter, I do like your version. The only thing I changed is the option name where I used the full `rpm_requirement_mode` name.

2022-04-05 12:14 UTC, portante approved these changes

2022-04-06 17:06 UTC, webbnh approved these changes
👍

2022-04-06 17:27 UTC, merged