Delete the spurious pbench3-devel RPM dependency
distributed-system-analysis/pbench pull request #2799
Opened 2022-04-28 21:41 UTC by ndokos

Fixes #2798

AFAICT, the python3-devel dependency (which only exists for RHEL7) is
spurious and in fact harmful: there seems to be no python3-devel
package for RHEL7.9, so installation fails with an unsatisfied
dependency, whereas an RPM built without it installs without
problems.

2022-04-28 23:56 UTC, webbnh submitted a review, later dismissed
Do we need `gcc`?  😁

2022-04-29 00:54 UTC, portante requested changes
Looks good.  We should double check, but I don't think we need `gcc` as a result of removing this dependency.

2022-04-29 12:25 UTC, dbutenhof submitted a review, later dismissed
Interesting...

2022-04-29 20:34 UTC, portante approved these changes

2022-04-29 20:47 UTC, dbutenhof approved these changes

2022-04-29 21:43 UTC, webbnh approved these changes
🎉

2022-04-30 01:56 UTC, merged