Minor Bug fixes in dashboard
distributed-system-analysis/pbench pull request #2873
Opened 2022-05-27 11:31 UTC by shubham-html-css-js

PR #2850 which was an incremental clean up on PR #2733, induced a bug in search feature of browsing page.This PR is an attempt to fix that bug.There is an addition of two important edge case also.

2022-05-27 11:58 UTC, dbutenhof submitted a review, later dismissed

2022-05-27 18:05 UTC, webbnh submitted a review, later dismissed

2022-05-28 01:55 UTC, portante requested changes
We need a Jira issue for this PR.

2022-05-31 06:19 UTC, MVarshini submitted a review, later dismissed

2022-06-01 14:20 UTC, webbnh approved these changes
👍

2022-06-01 15:22 UTC, merged