PBENCH-667: Use URI parameterization where reasonable
distributed-system-analysis/pbench pull request #2877
Opened 2022-06-01 19:45 UTC by npalaska

This PR addresses the remaining items for our efforts to move the resource (dataset name) from a JSON payload to the URI parameter. 

\
Commit_1: Add the dataset resource name to the URI as `/datasets/delete/<dataset>` PBENCH-673
Old: 
```
POST /datasets/delete
{name: <dataset_name>}
```
New: 
```
POST /datasets/delete/<dataset_name>
```

\
Commit_2: Add the dataset resource name to the URI as `/datasets/publish/<dataset>` PBENCH-674
Old: 
```
POST /datasets/publish
{"name": <dataset_name>, "access": <public/private>}
```
New: 
```
POST /datasets/publish/<dataset_name>
{"access": <public/private>}
```

\
Commit_3: Add the dataset resource name to the URI as `/datasets/contents/<dataset>` PBENCH-675
Old: 
```
POST /datasets/contents
{"name": <dataset_name>, "parent": <dataset_parent_name>}
```
New: 
```
POST /datasets/contents/<dataset_name>
{ "parent": <dataset_parent_name>}
```

2022-06-01 20:29 UTC, dbutenhof approved these changes
That's an interesting way to do it. I'll be checking to see whether Jira handles the tags from the three separate commits correctly. 🤞🏻 👀

2022-06-01 20:48 UTC, webbnh requested changes
There's one test parameterization which I think needs tweaking.  Otherwise, this looks good to me, although we might want to discuss shifting other body parameters to, say, query string parameters.

2022-06-01 20:48 UTC, webbnh commented on lib/pbench/server/api/resources/query_apis/datasets/datasets_contents.py
>                  ),
And, maybe `/datasets/publish/<dataset>` `"access"`, too?

2022-06-01 20:52 UTC, webbnh commented
> > That's an interesting way to do it. I'll be checking to see whether Jira handles the tags from the three separate commits correctly. 🤞🏻 eyes
> 
> BTW: I didn't expect it'd be that fast (we seem to be cycling now in under an hour); but indeed all three sub-tasks now show a linked open PR. Dang, it's amazing when computers actually work!

Unfortunately for the purposes of SCIENCE, @npalaska put the Jira tags both in the PR description and in the Git commit logs...so, we don't know which one ticked the integration....

2022-06-01 21:00 UTC, dbutenhof commented
> > > That's an interesting way to do it. I'll be checking to see whether Jira handles the tags from the three separate commits correctly. 🤞🏻 eyes
> > 
> > 
> > BTW: I didn't expect it'd be that fast (we seem to be cycling now in under an hour); but indeed all three sub-tasks now show a linked open PR. Dang, it's amazing when computers actually work!
> 
> Unfortunately for the purposes of SCIENCE, @npalaska put the Jira tags both in the PR description and in the Git commit logs...so, we don't know which one ticked the integration....

Jira integration reads the PR *title*, but he referenced the parent issue with an underscore instead of a hyphen. Jira doesn't read the PR description:

1. Branch name
2. PR title
3. Git commit log message

2022-06-01 21:30 UTC, webbnh commented
> > Unfortunately for the purposes of SCIENCE, @npalaska put the Jira tags both in the PR description and in the Git commit logs...so, we don't know which one ticked the integration....
> 
> Jira integration reads the PR _title_, but he referenced the parent issue with an underscore instead of a hyphen. Jira doesn't read the PR description:

Ah...well, _all_ the Jira tag references in the description used underscores, so that makes the result clear.

I just fixed the PR title, so we can see if the the parent Jira gets linked, now.

2022-06-02 13:58 UTC, npalaska commented on lib/pbench/test/unit/server/query_apis/test_datasets_contents.py
> +        incorrect_endpoint = "/".join(self.pbench_endpoint.split("/")[:-1]) + f"/{name}"
Yeah, I think it makes sense to drop the `None` parameter. I thought about that but I just kept it because the test didn't fail :grin:.

2022-06-02 16:12 UTC, dbutenhof approved these changes

2022-06-02 17:47 UTC, npalaska commented
> I just fixed the PR title, so we can see if the parent Jira gets linked, now.

It did get linked. However, I am not sure if we always want to link the parent Jira issue with that of the child issue's PR, that will create some confusion as there will be multiple child issues that will be resolved with separate PRs. Or is it possible to have multiple PRs linked to a Jira issue? :thinking:

2022-06-02 19:52 UTC, webbnh commented
> I am not sure if we always want to link the parent Jira issue with that of the child issue's PR

No, I'm sure that we won't want to in all cases; however, I'm equally sure that we shouldn't use underscore'd Jira tags to try to give humans a pointer while _avoiding_ the Jira integration.  😉 

> is it possible to have multiple PRs linked to a Jira issue? 🤔

I believe that a single Jira issue can be linked to multiple PRs (and other things).

2022-06-02 19:53 UTC, webbnh approved these changes
👍

2022-06-02 20:56 UTC, webbnh approved these changes
👍

2022-06-03 02:28 UTC, portante requested changes
Please add more detail about what is being done and why to the PR description and/or the commit message.

We need to avoid hiding the whats and whys in Jira issues only.

2022-06-03 11:02 UTC, dbutenhof approved these changes

2022-06-06 17:56 UTC, portante approved these changes

2022-06-06 17:58 UTC, merged