Fix agent ansible and python dependencies - backport to b0.71
distributed-system-analysis/pbench pull request #2902
Opened 2022-06-17 03:49 UTC by ndokos

This is a backport of #2901 to b0.71.

2022-06-17 11:54 UTC, dbutenhof submitted a review, later dismissed
Looks like what we agreed. Makes me wish we had a functional test system that would show a reviewer clearly that this all works. 😆

2022-06-17 16:18 UTC, portante commented
Set to `Draft` until #2901 is resolved.

2022-06-17 22:52 UTC, webbnh approved these changes
👍

2022-06-25 01:33 UTC, portante requested changes
This needs updating now that PR #2901 has been merged.

2022-06-27 11:24 UTC, dbutenhof commented
Unless my Chrome is refusing to update the view (which *has* happened), you're showing merge conflicts and it's still marked Draft. ???

2022-06-27 13:16 UTC, ndokos commented on utils/rpm.mk
> +	jinja2 ${prog}.spec.j2 targets.json -D version=${VERSION} -D gdist=g${sha1} -D seqno=${seqno} > ${RPMSPEC}/${prog}.spec
OK - I'll open an issue and try to fix it (against main, not against b0.71).

2022-06-27 20:20 UTC, npalaska approved these changes

2022-06-29 03:13 UTC, ndokos commented
Closing this PR in favor of #2927 which produces identical results and simplifies the implementation considerably.

2022-06-29 03:13 UTC, closed without merging

2022-07-06 17:01 UTC, portante commented
FWIW, the `Backport` label is used to mark PRs which should be back-ported, not PRs that _are_ backports.