Added link to list of official RH projects, changed time
distributed-system-analysis/pbench pull request #2962
Opened 2022-08-05 17:22 UTC by inntran

The year 2015 was from very first commit of the repo.
I added link to RH official project list because we want to help combating a recent supply chain attack.

2022-08-05 18:09 UTC, dbutenhof submitted a review, later dismissed

2022-08-08 17:50 UTC, dbutenhof approved these changes

2022-08-09 00:30 UTC, webbnh requested changes
So close!  😀

2022-08-09 00:30 UTC, webbnh commented on docs/gh-pages/doc.html
> +                    <<p class="darkFoot">2015 - 2022 Pbench | <a href="https://redhatofficial.github.io/#!/main">A Red Hat Community Project</a> | Privacy Statement</p>
I think there's an extra `<` at the beginning of the line.

2022-08-09 19:03 UTC, portante approved these changes

2022-08-09 19:10 UTC, dbutenhof approved these changes

2022-08-09 23:34 UTC, webbnh approved these changes
👍

2022-08-09 23:40 UTC, merged