Return `409 (CONFLICT)` on duplicate upload
distributed-system-analysis/pbench pull request #3150
Opened 2023-01-05 22:15 UTC by portante

We want to respond with an error message with the reason we did NOT read the `PUT` payload body.

2023-01-05 22:24 UTC, webbnh requested changes
I think returning `200` (as opposed to `201`) is actually good.

There's no actual conflict as, were the upload to proceed properly, we would ultimately determine that the resource as presented already existed, and so the upload operation was, in effect, successful (i.e., after the upload, the resource exists on the server).

A conflict would result if the server were presented with the same resource name or ID with different contents.  But, since we can tell that the contents (and therefore the resource itself) are the same, there should be no conflict.

2023-01-05 22:32 UTC, portante commented
I don't believe an API should ignore the body and return a 200, and I don't think it should consume the body if it doesn't have to.

This might be a mute point from the clients point of view with the way we are using Nginx because the reverse proxy will read the entire request before forwarding to the API server.  However, we'll see lots of Nginx messages saying upstream closed the connection prematurely.

2023-01-05 23:47 UTC, webbnh commented
> I don't believe an API should ignore the body and return a 200

I think the return status should reflect the result of the request, and, in this case, I think that `200` is an adequate representation of the result.

> I don't think it should consume the body if it doesn't have to.

I think I agree, depending on what you mean by "consume".  From the Pbench Server's perspective, as soon as we can figure out that we've already got that result, we can return `200` and we shouldn't need to read or process the payload.  From the client's perspective, as soon as they get the `200`, they can stop sending data (if the protocol that they are using permits that sequencing).

> This might be a [moot] point from the clients point of view with the way we are using Nginx because the reverse proxy will read the entire request before forwarding to the API server. However, we'll see lots of Nginx messages saying upstream closed the connection prematurely.

If this were to prove to be a real problem, I think there are ways under the HTTP protocol to deal with it (there's the `100`/`Continue` handshake), but I doubt that we'll see "lots of messages" because I doubt that we'll have lots of duplicate uploads, so we'll rarely be in a position to return `200`.

2023-01-06 01:58 UTC, portante commented
> I don't believe an API should ignore the body and return a 200, and I don't think it should consume the body if it doesn't have to.

While I still hold to the 2nd assertion (an API should not consume the body for no reason if it already knows its response), and reviewing the code shows that we don't do that today, I am hard pressed to demonstrate unwanted behaviors in our deployed server for the first.

That is to say, when we return a `200` for a duplicate entry we are not reading the body off the wire (at least where I can see by our code).  I had expected this to result in the reverse proxy reporting that the upstream stream server prematurely closed the connection before responding for a successful status message.

But that is not the case.  There are no error messages being reported by Nginx in our configuration.

The only behavior we might want to address is the fact that we are logging "warning" messages for these duplicates.

2023-01-06 01:58 UTC, closed without merging

2023-01-06 11:58 UTC, dbutenhof commented
> I had expected this to result in the reverse proxy reporting that the upstream stream server prematurely closed the connection before responding for a successful status message.

But this was supposed to be the entire point of the NGINX buffering configuration, and the part of the NGINX transition I was most anticipating!

I'm working on testing my resurrected duplicate/error test cases from #3103 ... I just wasn't managing to pull the new NGINX-based container yesterday afternoon.

2023-01-06 14:08 UTC, portante commented
> > I had expected this to result in the reverse proxy reporting that the upstream stream server prematurely closed the connection before responding for a successful status message.
> 
> But this was supposed to be the entire point of the NGINX buffering configuration, and the part of the NGINX transition I was most anticipating!

I am not sure I follow.  The client opens a connection to Nginx, and Nginx reads the entire client header and body.  Then Nginx opens a connection to the upstream server, and sends the header, but the upstream server has only read the header and NOT started reading the body when it responds with a 200.

I was expecting that Nginx would have reported "upstream server closed the connection prematurely" but it doesn't.  I am okay with that behavior, but I am going to verify it with `strace` today.

2023-01-06 14:12 UTC, webbnh commented
What you're describing sounds almost exactly like how I think we would want it to work.  (Yay?)

If Nginx receives the Server's response before the Server finishes reading the payload (or, particularly, if it's received between the headers and the payload), then I would think that Nginx can conclude that all is good, and, therefore, it doesn't need to report any issues.

There would be an issue if the connection to the server were closed without a response, but, given that Nginx has what it needs to conclude the transaction with the client, what would be the issue?

2023-01-06 14:14 UTC, dbutenhof commented
> I was expecting that Nginx would have reported "upstream server closed the connection prematurely" but it doesn't. I am okay with that behavior, but I am going to verify it with `strace` today.

Wow; I'm really confused. You shut down #3103, which "fixed" the server to consume the payload, with

> No, we do not want to have our internal pbench server PULL all data down when we don't have to. That is the whole point of the proxy servers. They do all that lifting, so we can respond to requests by just looking at the headers.

Now you're saying you don't expect that would be a solution after all?

However, my experimentation this morning (#3152) confirms that it *does* work as I (but apparently not you?) expected.

2023-01-06 17:03 UTC, portante commented
> What you're describing sounds almost exactly like how I think we would want it to work. (Yay?)

Almost.  I was expecting that a successful response code required that the server read the entire payload of the request, and that an error response code would NOT require the server to read the entire payload.

So returning a 409, or 400, or any other error code would be normal an expected.

What is still weird to me is to see a 200 success code and the payload not read.

Imagine that we received a 201 success code and the payload was not read.  The client experiences its payload being read because Nginx buffers it, but if our API server does not read the entire contents of the buffer it is in error.

For a 200, we are not reading all the data and verifying that the payload contents match the MD5 header value, and just returning success.  This means I can mistakenly a mismatch between header and body won't be detected on the success case.

This is why I am confused.  I would rather us return a 400 or a 409 on an upload for which the data was already present because then we can safely define the error condition to be determined only from the headers and not the body.

But with a 200 success, the client thinks it did the right thing, and we blindly confirm it without verifying the body.  An error in transmission where the body no longer matches the header would not be caught, but we'd still return a 200.

2023-01-06 17:12 UTC, dbutenhof commented
> But with a 200 success, the client thinks it did the right thing, and we blindly confirm it without verifying the body. An error in transmission where the body no longer matches the header would not be caught, but we'd still return a 200.

The idea was that retries work. There's no point in diagnosing a corrupted transmission as we already have all the data. We could be more paranoid by pulling the whole payload and checking it, but that seems like extra work with no real value. Sure, someone could do a `PUT` with the same name and MD5 and a garbage or empty stream, and what they get, realistically, is simply a confirmation that the dataset already exists.

Ha: actually, you're not entirely wrong anyway, because there's another condition here I just considered. In theory, this would allow snooping for datasets you're not allowed to see. Though I don't see a lot of value, we could add a check to the duplicate detection to confirm that the existing dataset is owned by you or public, and otherwise fail with a 400. (I'm not sure about `CONFLICT` here, though, as that still confirms that the name exists.)

2023-01-06 17:23 UTC, portante commented
> > But with a 200 success, the client thinks it did the right thing, and we blindly confirm it without verifying the body. An error in transmission where the body no longer matches the header would not be caught, but we'd still return a 200.
> 
> The idea was that retries work.

I don't think there is much value in that.  If I get a 201, I'm good.  If I try again, I should be told it is already there.  We are saying that using a 200, but our code is not reading the payload when responding with a 200 and that just is confusing to me.

I have tried multiple times to explain why it is confusing to me, but I am failing to convey my confusing.

I have closed this PR and I am NOT suggesting we change to using a 409 anymore.

> There's no point in diagnosing a corrupted transmission as we already have all the data. We could be more paranoid by pulling the whole payload and checking it, but that seems like extra work with no real value. Sure, someone could do a `PUT` with the same name and MD5 and a garbage or empty stream, and what they get, realistically, is simply a confirmation that the dataset already exists.

But not with the same data they sent.  I am just not comfortable with the 200 response code, but if you all are okay with it, great.  That is why I have withdrawn this change.

> 
> Ha: actually, you're not entirely wrong anyway, because there's another condition here I just considered. In theory, this would allow snooping for datasets you're not allowed to see. Though I don't see a lot of value, we could add a check to the duplicate detection to confirm that the existing dataset is owned by you or public, and otherwise fail with a 400. (I'm not sure about `CONFLICT` here, though, as that still confirms that the name exists.)

Yes, we need to close this hole and verify the tar is owned by the client or is public  before returning a 200.

2023-01-06 17:48 UTC, webbnh commented
> I was expecting that a successful response code required that the server read the entire payload of the request, and that an error response code would NOT require the server to read the entire payload.
> 
> So returning a 409, or 400, or any other error code would be normal an expected.
> 
> What is still weird to me is to see a 200 success code and the payload not read.

The client receiving the `200` cannot tell that the payload was not read.  Moreover, assuming that the Pbench Server can correctly decide that a `200` is the appropriate response, I don't think I care how much of the request it reads.  (I.e., the less the better, right??)

That is, if the response is correct, it really shouldn't matter (much) what the server (and proxy) do to produce it, at least from the client perspective.  (And, from the server perspective, anything that we can do to make it more efficient -- like not reading the payload -- is a Good Thing™.)

> Imagine that we received a 201 success code and the payload was not read. The client experiences its payload being read because Nginx buffers it, but if our API server does not read the entire contents of the buffer it is in error.

If the server can _correctly_ return a `201` without reading the payload, then I believe that there is no problem.  If the server is **incorrectly** returning a `201`, then there is a problem regardless of whether it reads the whole request.  (Yes, from an operational perspective, we can agree that it seems unlikely that the server could correctly return a `201` without reading the whole request, but that's not the issue -- the issue is whether the response is correct, and that has to be determined separately, based principally on what the client can see, which does not include how the server handled the request.)

> For a 200, we are not reading all the data and verifying that the payload contents match the MD5 header value, and just returning success. This means I can mistakenly a mismatch between header and body won't be detected on the success case.

If the header value is correct (and if the hash is acting properly), then there is no point in reading the body if the Server already has a matching result:  if the body matches the header, then we didn't gain anything by reading it (i.e., we would return a `200` whether we read it or not); if the body doesn't match the header, then it's a malformed request.  If there is a mismatch, then, in all likelihood, the header is correct and the payload is bad, and so spending the time to read the payload doesn't produce sufficient value in that case, either.

> This is why I am confused. I would rather us return a 400 or a 409 on an upload for which the data was already present because then we can safely define the error condition to be determined only from the headers and not the body.
> 
> But with a 200 success, the client thinks it did the right thing, and we blindly confirm it without verifying the body. An error in transmission where the body no longer matches the header would not be caught, but we'd still return a 200.

In the case of a duplicate upload, the client _did_ do a reasonable thing, and the Server confirms that it already has it, and any error in transmission of the duplicate really isn't important.  (Who cares if the retry-failed given that the initial upload worked??)

> In theory, this would allow snooping for datasets you're not allowed to see.

That's only true if you can _guess_ their MD5 hash code, which should be statistically impossible.  (And, even if you could, what would you gain by doing so?  "Oh, that result is already on the server...but not owned by me...."  That doesn't seem like much of a leak.)

The better issue to tangle with is, how should we address the case of two separate users trying (for whatever reason) to upload the _same result_?  The first one gets the `201`; the second get a `200` (I think...), but then cannot **see** the data!  They each, presumably, have the right to upload and view the data, but the second one is shut out by the first....  (In all likelihood, this is a non-problem which we eventually will be able to address by having the first user grant access to the second user, but...it's a (slightly) interesting problem from a UX perspective.)

2023-01-06 17:52 UTC, dbutenhof commented
> The better issue to tangle with is, how should we address the case of two separate users trying (for whatever reason) to upload the _same result_? The first one gets the `201`; the second get a `200` (I think...), but then cannot **see** the data! They each, presumably, have the right to upload and view the data, but the second one is shut out by the first.... (In all likelihood, this is a non-problem which we eventually will be able to address by having the first user grant access to the second user, but...it's a (slightly) interesting problem from a UX perspective.)

In that case I'd definitely prefer *not* to return a 200 for the second. Although two users on the same test system simultaneously uploading the same dataset is such an unusual condition I doubt it really matters. But I'm inclined to return a different error there. 409 would still enable "snooping" (to the extent that concern even makes sense), and I'm not sure there's a better error here.

2023-01-06 18:45 UTC, webbnh commented
I'm inclined to agree that returning `200` to a user for a result which they cannot access would be a Bad Thing™...but, I'm really not sure it's worth the extra code.  (That is, in order for this to occur, Dave and Pete would have to share a single result and then both independently decide to upload it using their own respective login tokens...which seems unlikely.)

I think that returning `409` in that case would actually be appropriate.  It's "statistically impossible" that it would enable snooping, and it properly describes the reason why the result cannot be uploaded.  (I.e., "You cannot upload that result because someone else already owns it on our server, even though you apparently are in possession of the data.")