Rework how we name Server container images
distributed-system-analysis/pbench pull request #3215
Opened 2023-01-27 21:26 UTC by webbnh

_NOTE:  This PR is an extension of #3214, and, until it is merged, the commit(s) from that branch will show up in this one._

This PR reworks some of how we refer to Pbench Server container images.  A container image name consists of three parts:  a registry name, a repository name, and an image tag; the repository is further subdivided in most of our registries to include an organization prefix and an image suffix.  Currently, when we push an image, we compose an image name from a registry, our organization, and the image suffix (plus a tag); however, when we build the image and store it locally, we use `localhost` instead of the remote registry and organization.  This dichotomy is not strictly necessary.

Instead, this PR changes our usage to always name an image using the remote (target) registry, the `pbench` organization, and the image suffix, *even when storing the image locally*.  This removes the dichotomy, and it allows a given image to have the same name regardless of where it is stored.  (This is not strange:  in a typical case, when one pulls an image from a remote registry, it appears in the local registry with the remote registry in its name; correspondingly, when building an image it is stored in the local registry, and it can be named using the remote registry, which allows it to be `push`'d using a single argument.)

2023-01-27 22:33 UTC, webbnh commented
Whoops; this one is to stay in draft until #3214 lands.

2023-01-30 22:22 UTC, portante requested changes

2023-01-30 22:24 UTC, portante commented on server/pbenchinacan/container-build.sh
> +# Copy the Pbench Server config file for our "in-a-can" environment, and
Previous comment is in the previous commit.  Sorry.

2023-02-01 17:04 UTC, dbutenhof reviewed
No objection in principle as long as podman and buildah are happy.

2023-02-16 19:16 UTC, webbnh commented
As was [foretold in prophecy](https://github.com/distributed-system-analysis/pbench/pull/3215#issuecomment-1412587614), this PR shall now be closed.

2023-02-16 19:16 UTC, closed without merging