Add ability to auto-generate alembic migrations
distributed-system-analysis/pbench pull request #3225
Opened 2023-02-02 15:05 UTC by portante

We move to a slightly more general model where we can support specific Alembic operations passed as arguments.

This was very useful to easily run the auto-generated migrations.

2023-02-02 16:00 UTC, dbutenhof approved these changes

2023-02-02 16:45 UTC, webbnh requested changes
After this morning's discussions, I would like to see this rebased on ~#3203, which is now ready to merge pending one more approval~ `main`.

2023-02-05 15:01 UTC, portante reviewed
Rebased on #3211 and now depends on that PR.

2023-02-06 15:39 UTC, webbnh approved these changes
👍 

(I recognize that this PR is in draft mode, but I'm trying to stay ahead of the curve, here.)

2023-02-07 16:18 UTC, portante reviewed
Ready for review.

2023-02-07 16:35 UTC, dbutenhof approved these changes

2023-02-07 17:02 UTC, merged