UI to interact with Relay server
distributed-system-analysis/pbench pull request #3484
Opened 2023-07-07 10:21 UTC by MVarshini

PBENCH-1141

Develop UI to interact with Relay server 'pull' API

2023-07-07 12:08 UTC, dbutenhof requested changes
This is great; you seem to have some duplicate code to clean up, plus we need to finalize the header in the dialog.

2023-07-07 12:08 UTC, dbutenhof commented on dashboard/src/actions/relayActions.js
> +      : ERROR_MSG;
I think Webb somewhere suggested ```error?.response?.data?.message ?? `Error: ${error}` ```

2023-07-07 15:27 UTC, MVarshini commented on dashboard/src/actions/relayActions.js
> +    if (response.status >= 200 && response.status < 300) {
In axios, there is `ok` attribute in the response object

2023-07-07 15:28 UTC, MVarshini commented on dashboard/src/modules/components/RelayUIComponent/index.jsx
> +      <div>To pull the dataset</div>
Added the content

2023-07-07 15:28 UTC, MVarshini commented on dashboard/src/App.js
> +                    />
Removed it

2023-07-07 15:28 UTC, MVarshini commented on dashboard/src/actions/relayActions.js
> +      : ERROR_MSG;
Yes, I remember it now

2023-07-07 15:55 UTC, dbutenhof approved these changes

2023-07-07 15:55 UTC, dbutenhof commented on dashboard/src/modules/components/RelayUIComponent/index.jsx
> +      <div>To pull the dataset</div>
I like the fly-over info idea, although we might want more "inline" text than just "Relay", as well. We may have to iterate on this, but that's OK!

2023-07-07 15:55 UTC, dbutenhof commented on dashboard/src/actions/relayActions.js
> +    if (response.status >= 200 && response.status < 300) {
I'm curious why you didn't use `if (response.ok)` here, then? It's not a problem, and I think this will work just fine.

2023-07-10 16:00 UTC, webbnh approved these changes
This looks good (and so I'm approving), but I've pointed out some opportunities for polishing if you feel inclined.

2023-07-11 10:39 UTC, MVarshini commented on dashboard/src/actions/relayActions.js
> +    });
Gotcha

2023-07-11 10:39 UTC, MVarshini commented on dashboard/src/modules/components/RelayUIComponent/index.jsx
> +  return (
Updated

2023-07-11 10:39 UTC, MVarshini commented on dashboard/src/modules/components/RelayUIComponent/index.jsx
> +      to begin the import.
Replaced

2023-07-11 10:40 UTC, MVarshini commented on dashboard/src/modules/components/RelayUIComponent/index.jsx
> +      reached by both the Pbench Agent and the Pbench Server.{" "}
Removed it

2023-07-11 10:40 UTC, MVarshini commented on dashboard/src/modules/components/RelayUIComponent/index.jsx
> +    dispatch(toggleRelayModal(false));
Renamed the function

2023-07-11 12:24 UTC, dbutenhof approved these changes

2023-07-11 12:24 UTC, dbutenhof commented on dashboard/src/actions/relayActions.js
> +      }
@MVarshini : despite this comment, it's probably best to leave the code alone for now and come back later.

However, for what it's worth, if you want to think about your refresh optimization ideas, I've updated the staging server with the latest code from `main`. I restarted the relay and pushed a dataset, and now (omitting the internal hostnames from GitHub comments):

```
POST https://<staging-server>/api/v1/relay/http://<relay>:8002/RELAY/4bcada96aff3b1d9a62540962204c833c12cd9266b10d747e1ef71b278d23a09
```

will return:

```json
{
    "message": "File successfully uploaded",
    "name": "pbench-user-benchmark_newrelay_2023.07.11T12.04.37",
    "resource_id": "a9b1daaa5549c4063c00e1d62115c9e5"
}
```

2023-07-11 12:24 UTC, dbutenhof commented on dashboard/src/actions/relayActions.js
> +    dispatch({ type: TYPES.NETWORK_ERROR });
I'm not sure I understand that, either: I haven't noticed anything that sets a `payload` value, but the actions here and in the visualizer PR both use this unconditionally when errors occur, but I don't see any implementation of that type code.

2023-07-11 13:00 UTC, merged